### ISSUE TITLE
Can not perform DFU update (Error: Error 7: The specified device has disconnected from us.)

### ISSUE THREAD

**Issue by rmuchev** [NordicSemiconductor/IOS-nRF-Toolbox#29]
Hi,

Can not perform DFU update.
Receiving Error: Error 7: The specified device has disconnected from us.
Log and screenshot attached. Tested on iOS 9 & 10.

Best regards,
Risto

![img_0131](https://cloud.githubusercontent.com/assets/3510485/19456203/9ba4f00a-94c0-11e6-8f9d-86fb9505a7c3.jpg)
[nRF_log.txt](https://github.com/NordicSemiconductor/IOS-nRF-Toolbox/files/534730/nRF_log.txt)

**Comment by mostafaberg** [comment]
I see this is an InuHeat devcice, you will need to get in touch with someone at InuHeat as this was a firmware bug they had related to the `CCCD / Service changed` notification not being implemented, your only workaround is to use the android client to do that since there is a workaround implemented in android that we can't implement on iOS since it doesn't follow the standards.

will close issue as it's not related to `nRF-Toolbox` nor `iOSDFULibrary`
