### ISSUE TITLE
Scanning for the DFU Bootloader ...

### ISSUE THREAD

**Issue by HongCongZhi** [NordicSemiconductor/IOS-nRF-Toolbox#56]
I used DFU in IOS-nRF-Toolbox and prompted "Scanning for the DFU Bootloader ...", it didn't respond.

**Comment by hy15816** [comment]
@philips77 
I found the same problem.
Just like this one: 
![企业微信截图_8bb589ab-2f27-4efd-ad95-1b4708437cfe](https://user-images.githubusercontent.com/12286011/62260599-12a42080-b445-11e9-926d-0f2634bf7cbe.png)

The program stays there any times,and peripheral always connented .Disconnect only when power is cut off。
The DFU Library verstion is 4.1.1 
iOS 12.3   - iPhone 7
xcode 10.1 (10B61)

Can you help me ？ or give me some suggests, thank you!

**Comment by philips77** [comment]
Hello, sorry for replying so late.
This issue is related to DFU Library, and an older version of it. It has been fixed with https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/pull/367 and released in version 4.7.1. Please use most current version of the DFU library (which right now is 4.10.1, released today).
